version: 2

sources:
  - name: pagila
    description: "base models"
    # database:
    freshness: # default freshness
      warn_after: { count: 123456789, period: day }
      error_after: { count: 999999999, period: day }
    loaded_at_field: last_update
    schema: public
    tables:
      - name: actor
        meta:
          owner: "@alice"
          model_maturity: in dev
          some_other_property: test 1
      - name: address
        description: "a user's address"
      - name: category
        description: "a user's category"
      - name: city
      - name: country
        meta:
          owner: "@bob"
          model_maturity: in prod
          some_other_property: test 2
      - name: customer
      - name: payment_p2020_01
        identifier: payment_p2020_01
        loaded_at_field: payment_date
      - name: payment_p2020_02
        identifier: payment_p2020_02
        loaded_at_field: payment_date
        meta:
          owner: "@charles"
          model_maturity: in prod
          some_other_property: test 3
          an_array_property: ["alpha", "beta", "charlie"]
      - name: payment_p2020_03
        identifier: payment_p2020_03
        loaded_at_field: payment_date
      - name: payment_p2020_04
        identifier: payment_p2020_04
        loaded_at_field: payment_date
      - name: payment_p2020_05
        identifier: payment_p2020_05
        loaded_at_field: payment_date
        description: "a payment"
      - name: payment_p2020_06
        identifier: payment_p2020_06
        loaded_at_field: payment_date
